--- !ruby/object:VR_ENV
settings_file_version: 1
width: 800
height: 600
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- "/home/david/CSE-3901/SetGUI/main.rb"
- "/home/david/CSE-3901/SetGUI/bin/MyClass.rb"
open_folders:
- "/home/david/CSE-3901"
- "/home/david/CSE-3901/SetGUI"
- "/home/david/CSE-3901/SetGUI/bin"
- "/home/david/CSE-3901/SetGUI/bin/glade"
current_file: "/home/david/CSE-3901/SetGUI/bin/MyClass.rb"
rdoc_command_line: rdoc -x README
